### ISSUE TITLE
my pterodactyl stopped working upon installing the plugin panel

### ISSUE THREAD

**Issue by Plaguewave7** [Jexactyl/plugin-manager-addon#6]
my panel just wound up killing itself, I can't access my servers now, It keeps saying "something went wrong" how do I fix this? 

![image](https://github.com/Jexactyl/plugin-manager-addon/assets/71691723/6488d802-9574-4c77-b949-3f804168f714)

**Comment by Plaguewave7** [comment]
I fixed my panel, so this isn't an issue anymore

**Comment by AxionQc** [comment]
> I fixed my panel, so this isn't an issue anymore

How?
